# Generated by Django 5.2 on 2025-05-23 14:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.RemoveField(
        model_name='wordpair',
        name='user',
    ),
    migrations.AddField(
        model_name='wordpair',
        name='author',
        field=models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            to=settings.AUTH_USER_MODEL,
            null=True,
            blank=True,
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='wordpair',
        name='created_at',
        field=models.DateTimeField(auto_now_add=True),
    ),
    migrations.AddField(
        model_name='wordpair',
        name='is_public',
        field=models.BooleanField(default=True),
    ),
    migrations.AddField(
        model_name='wordpair',
        name='likes',
        field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
    ),
    migrations.AddField(
        model_name='wordpair',
        name='saved_by',
        field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
    ),
    migrations.AlterField(
        model_name='wordpair',
        name='output_text',
        field=models.CharField(max_length=255),
    ),
]

