# Generated by Django 5.2 on 2025-05-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wordpair_user_wordpair_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpair',
            old_name='author',
            new_name='user',
        ),
    ]
